//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnbConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XnbConverter.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid magic value found, {0}.
        /// </summary>
        public static string AudioEngineReader_1 {
            get {
                return ResourceManager.GetString("AudioEngineReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name index offset: {0}.
        /// </summary>
        public static string AudioEngineReader_10 {
            get {
                return ResourceManager.GetString("AudioEngineReader.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name index offset: {0}.
        /// </summary>
        public static string AudioEngineReader_11 {
            get {
                return ResourceManager.GetString("AudioEngineReader.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name offset: {0}.
        /// </summary>
        public static string AudioEngineReader_12 {
            get {
                return ResourceManager.GetString("AudioEngineReader.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name offset: {0}.
        /// </summary>
        public static string AudioEngineReader_13 {
            get {
                return ResourceManager.GetString("AudioEngineReader.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC offset: {0}.
        /// </summary>
        public static string AudioEngineReader_14 {
            get {
                return ResourceManager.GetString("AudioEngineReader.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP preset offset: {0}.
        /// </summary>
        public static string AudioEngineReader_15 {
            get {
                return ResourceManager.GetString("AudioEngineReader.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP parameter offset: {0}.
        /// </summary>
        public static string AudioEngineReader_16 {
            get {
                return ResourceManager.GetString("AudioEngineReader.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}.
        /// </summary>
        public static string AudioEngineReader_17 {
            get {
                return ResourceManager.GetString("AudioEngineReader.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable: {0}.
        /// </summary>
        public static string AudioEngineReader_18 {
            get {
                return ResourceManager.GetString("AudioEngineReader.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported XGS format!.
        /// </summary>
        public static string AudioEngineReader_19 {
            get {
                return ResourceManager.GetString("AudioEngineReader.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool version: {0}.
        /// </summary>
        public static string AudioEngineReader_2 {
            get {
                return ResourceManager.GetString("AudioEngineReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format version: {0}.
        /// </summary>
        public static string AudioEngineReader_3 {
            get {
                return ResourceManager.GetString("AudioEngineReader.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0}, Variable: {1}.
        /// </summary>
        public static string AudioEngineReader_4 {
            get {
                return ResourceManager.GetString("AudioEngineReader.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC: {0}.
        /// </summary>
        public static string AudioEngineReader_5 {
            get {
                return ResourceManager.GetString("AudioEngineReader.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP preset: {0}.
        /// </summary>
        public static string AudioEngineReader_6 {
            get {
                return ResourceManager.GetString("AudioEngineReader.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP parameters: {0}.
        /// </summary>
        public static string AudioEngineReader_7 {
            get {
                return ResourceManager.GetString("AudioEngineReader.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category offset: {0}.
        /// </summary>
        public static string AudioEngineReader_8 {
            get {
                return ResourceManager.GetString("AudioEngineReader.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable offset: {0}.
        /// </summary>
        public static string AudioEngineReader_9 {
            get {
                return ResourceManager.GetString("AudioEngineReader.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found!.
        /// </summary>
        public static string BufferReader_1 {
            get {
                return ResourceManager.GetString("BufferReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer search out of range! {0} ~ {1}.
        /// </summary>
        public static string BufferReader_2 {
            get {
                return ResourceManager.GetString("BufferReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value {0} does not correspond to any enum member..
        /// </summary>
        public static string EnumReader_1 {
            get {
                return ResourceManager.GetString("EnumReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output path {0}
        ///{1}.
        /// </summary>
        public static string FileUtils_1 {
            get {
                return ResourceManager.GetString("FileUtils.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input path: {0}.
        /// </summary>
        public static string FileUtils_2 {
            get {
                return ResourceManager.GetString("FileUtils.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SoundEffect, only wav files in Pcm format are supported. The current format is {0}.
        /// </summary>
        public static string FmtChunk_1 {
            get {
                return ResourceManager.GetString("FmtChunk.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Xact, only wav files in Pcm or AdpcmMs format are supported. The current format is {0}.
        /// </summary>
        public static string FmtChunk_2 {
            get {
                return ResourceManager.GetString("FmtChunk.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a supported type for the game!.
        /// </summary>
        public static string FmtChunk_3 {
            get {
                return ResourceManager.GetString("FmtChunk.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WAV format: {0}, should be fmt.
        /// </summary>
        public static string FmtChunkReader_1 {
            get {
                return ResourceManager.GetString("FmtChunkReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value of i is {0}, current value is {1}.
        /// </summary>
        public static string LayerReader_1 {
            get {
                return ResourceManager.GetString("LayerReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile data error.
        /// </summary>
        public static string LayerReader_2 {
            get {
                return ResourceManager.GetString("LayerReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window size out of range!.
        /// </summary>
        public static string LZX_1 {
            get {
                return ResourceManager.GetString("LZX.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding table did not reach table mask..
        /// </summary>
        public static string LZX_10 {
            get {
                return ResourceManager.GetString("LZX.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size read in compressed content..
        /// </summary>
        public static string LZX_11 {
            get {
                return ResourceManager.GetString("LZX.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully decompressed!.
        /// </summary>
        public static string LZX_12 {
            get {
                return ResourceManager.GetString("LZX.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra digits: {0}.
        /// </summary>
        public static string LZX_13 {
            get {
                return ResourceManager.GetString("LZX.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position base: {0}.
        /// </summary>
        public static string LZX_14 {
            get {
                return ResourceManager.GetString("LZX.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel: {0} = {1}.
        /// </summary>
        public static string LZX_15 {
            get {
                return ResourceManager.GetString("LZX.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block type: {0} = {1}.
        /// </summary>
        public static string LZX_16 {
            get {
                return ResourceManager.GetString("LZX.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining block byte count: {0}.
        /// </summary>
        public static string LZX_17 {
            get {
                return ResourceManager.GetString("LZX.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0}, Bit mask: {1}, Table mask: {2}.
        /// </summary>
        public static string LZX_18 {
            get {
                return ResourceManager.GetString("LZX.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit count: {0}, Bit string: {1}.
        /// </summary>
        public static string LZX_19 {
            get {
                return ResourceManager.GetString("LZX.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel E8 call found, invalid for XNB file..
        /// </summary>
        public static string LZX_2 {
            get {
                return ResourceManager.GetString("LZX.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol: {0}, Symbol string: {1}.
        /// </summary>
        public static string LZX_20 {
            get {
                return ResourceManager.GetString("LZX.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------Block size: {0}, Frame size: {1}.
        /// </summary>
        public static string LZX_21 {
            get {
                return ResourceManager.GetString("LZX.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid block type found: {0}.
        /// </summary>
        public static string LZX_3 {
            get {
                return ResourceManager.GetString("LZX.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run outside the window frame..
        /// </summary>
        public static string LZX_4 {
            get {
                return ResourceManager.GetString("LZX.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range! {0} {1} {2}.
        /// </summary>
        public static string LZX_5 {
            get {
                return ResourceManager.GetString("LZX.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified block type invalid!.
        /// </summary>
        public static string LZX_6 {
            get {
                return ResourceManager.GetString("LZX.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOF reached, data still remaining..
        /// </summary>
        public static string LZX_7 {
            get {
                return ResourceManager.GetString("LZX.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table overflow!.
        /// </summary>
        public static string LZX_8 {
            get {
                return ResourceManager.GetString("LZX.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table overflow during decoding..
        /// </summary>
        public static string LZX_9 {
            get {
                return ResourceManager.GetString("LZX.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file saved: {0}.
        /// </summary>
        public static string Process_1 {
            get {
                return ResourceManager.GetString("Process.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be saved!.
        /// </summary>
        public static string Process_2 {
            get {
                return ResourceManager.GetString("Process.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename: {0} {1}.
        /// </summary>
        public static string Process_3 {
            get {
                return ResourceManager.GetString("Process.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename: {0} {1} {2}.
        /// </summary>
        public static string Process_4 {
            get {
                return ResourceManager.GetString("Process.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Enable concurrency.
        /// </summary>
        public static string Program_1 {
            get {
                return ResourceManager.GetString("Program.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected: {0}, please click the link to download: {1}.
        /// </summary>
        public static string Program_10 {
            get {
                return ResourceManager.GetString("Program.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Required] Input file or folder.
        /// </summary>
        public static string Program_2 {
            get {
                return ResourceManager.GetString("Program.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Required] Output folder.
        /// </summary>
        public static string Program_3 {
            get {
                return ResourceManager.GetString("Program.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pack and unpack XNB files based on input.
        /// </summary>
        public static string Program_4 {
            get {
                return ResourceManager.GetString("Program.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack.
        /// </summary>
        public static string Program_5 {
            get {
                return ResourceManager.GetString("Program.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Program_6 {
            get {
                return ResourceManager.GetString("Program.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad command.
        /// </summary>
        public static string Program_7 {
            get {
                return ResourceManager.GetString("Program.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch Exception:.
        /// </summary>
        public static string Program_8 {
            get {
                return ResourceManager.GetString("Program.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}
        ///Project URL: {2}
        ///Author Email: {3}.
        /// </summary>
        public static string Program_9 {
            get {
                return ResourceManager.GetString("Program.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map property type: {0}.
        /// </summary>
        public static string PropertieReader_1 {
            get {
                return ResourceManager.GetString("PropertieReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reader index {0}.
        /// </summary>
        public static string ReaderResolver_1 {
            get {
                return ResourceManager.GetString("ReaderResolver.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader not found, index: {0}.
        /// </summary>
        public static string ReaderResolver_2 {
            get {
                return ResourceManager.GetString("ReaderResolver.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WAV format: {0}, should be RIFF.
        /// </summary>
        public static string RIFFChunkReader_1 {
            get {
                return ResourceManager.GetString("RIFFChunkReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wav format: {0}, should be WAVE.
        /// </summary>
        public static string RIFFChunkReader_2 {
            get {
                return ResourceManager.GetString("RIFFChunkReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC: {0}.
        /// </summary>
        public static string SoundBankReader_1 {
            get {
                return ResourceManager.GetString("SoundBankReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple hint sound offset: {0}.
        /// </summary>
        public static string SoundBankReader_10 {
            get {
                return ResourceManager.GetString("SoundBankReader.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex hint sound offset: {0}.
        /// </summary>
        public static string SoundBankReader_11 {
            get {
                return ResourceManager.GetString("SoundBankReader.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound offset for names: {0}.
        /// </summary>
        public static string SoundBankReader_12 {
            get {
                return ResourceManager.GetString("SoundBankReader.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation table offset: {0}.
        /// </summary>
        public static string SoundBankReader_13 {
            get {
                return ResourceManager.GetString("SoundBankReader.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform library name table offset: {0}.
        /// </summary>
        public static string SoundBankReader_14 {
            get {
                return ResourceManager.GetString("SoundBankReader.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound name hash table offset: {0}.
        /// </summary>
        public static string SoundBankReader_15 {
            get {
                return ResourceManager.GetString("SoundBankReader.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound name hash value offset: {0}.
        /// </summary>
        public static string SoundBankReader_16 {
            get {
                return ResourceManager.GetString("SoundBankReader.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound offset: {0}.
        /// </summary>
        public static string SoundBankReader_17 {
            get {
                return ResourceManager.GetString("SoundBankReader.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string SoundBankReader_18 {
            get {
                return ResourceManager.GetString("SoundBankReader.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Banks: {0}.
        /// </summary>
        public static string SoundBankReader_19 {
            get {
                return ResourceManager.GetString("SoundBankReader.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification time low: {0}, Last modification time high: {1}.
        /// </summary>
        public static string SoundBankReader_2 {
            get {
                return ResourceManager.GetString("SoundBankReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cues: {0}.
        /// </summary>
        public static string SoundBankReader_20 {
            get {
                return ResourceManager.GetString("SoundBankReader.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0}.
        /// </summary>
        public static string SoundBankReader_21 {
            get {
                return ResourceManager.GetString("SoundBankReader.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {1} cues for {0}.
        /// </summary>
        public static string SoundBankReader_22 {
            get {
                return ResourceManager.GetString("SoundBankReader.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaveBank Index: {0}.
        /// </summary>
        public static string SoundBankReader_23 {
            get {
                return ResourceManager.GetString("SoundBankReader.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} cues!.
        /// </summary>
        public static string SoundBankReader_24 {
            get {
                return ResourceManager.GetString("SoundBankReader.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SoundBank format {0}..
        /// </summary>
        public static string SoundBankReader_25 {
            get {
                return ResourceManager.GetString("SoundBankReader.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform: {0}.
        /// </summary>
        public static string SoundBankReader_3 {
            get {
                return ResourceManager.GetString("SoundBankReader.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple hints: {0}.
        /// </summary>
        public static string SoundBankReader_4 {
            get {
                return ResourceManager.GetString("SoundBankReader.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex hints: {0}.
        /// </summary>
        public static string SoundBankReader_5 {
            get {
                return ResourceManager.GetString("SoundBankReader.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hints: {0}.
        /// </summary>
        public static string SoundBankReader_6 {
            get {
                return ResourceManager.GetString("SoundBankReader.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform libraries: {0}.
        /// </summary>
        public static string SoundBankReader_7 {
            get {
                return ResourceManager.GetString("SoundBankReader.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sounds: {0}.
        /// </summary>
        public static string SoundBankReader_8 {
            get {
                return ResourceManager.GetString("SoundBankReader.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue name table length: {0}.
        /// </summary>
        public static string SoundBankReader_9 {
            get {
                return ResourceManager.GetString("SoundBankReader.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse file failed.
        /// </summary>
        public static string SpriteFont_1 {
            get {
                return ResourceManager.GetString("SpriteFont.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xnb does not currently support Tbin maps with more than {0} layers, currently {1} layers.
        /// </summary>
        public static string TBin10Reader_1 {
            get {
                return ResourceManager.GetString("TBin10Reader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown program error.
        /// </summary>
        public static string TBin10Reader_2 {
            get {
                return ResourceManager.GetString("TBin10Reader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D format type ECT1 not implemented!.
        /// </summary>
        public static string Texture2DReader_1 {
            get {
                return ResourceManager.GetString("Texture2DReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unimplemented Texture2D format type ({0})..
        /// </summary>
        public static string Texture2DReader_2 {
            get {
                return ResourceManager.GetString("Texture2DReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Width: {0}, Height: {1}, Format: {2}.
        /// </summary>
        public static string Texture2DReader_3 {
            get {
                return ResourceManager.GetString("Texture2DReader.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found mipcount for {0}, only the first will be used..
        /// </summary>
        public static string Texture2DReader_4 {
            get {
                return ResourceManager.GetString("Texture2DReader.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension represented by the width and height of the Texture2D does not match the data size. Current width: {0}, height: {1}, data size: {2}.
        /// </summary>
        public static string Texture2DReader_5 {
            get {
                return ResourceManager.GetString("Texture2DReader.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unimplemented type: {0}
        ///{1}.
        /// </summary>
        public static string TypeReadHelper_1 {
            get {
                return ResourceManager.GetString("TypeReadHelper.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while obtaining reader! 
        /// Please check the assembly: {0} 
        /// Whether the corresponding DLL file path exists, or if the path is correctly written to the {1} file. 
        /// The DLL file may be {2}.dll 
        /// Error message: {3}.
        /// </summary>
        public static string TypeReadHelper_2 {
            get {
                return ResourceManager.GetString("TypeReadHelper.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unimplemented type: {0}.
        /// </summary>
        public static string TypeReadHelper_3 {
            get {
                return ResourceManager.GetString("TypeReadHelper.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not loaded: {0}!.
        /// </summary>
        public static string TypeReadHelper_4 {
            get {
                return ResourceManager.GetString("TypeReadHelper.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist, DLL loading failed, which may result in unsuccessful xnb parsing, 
        /// Please modify the correct file path to {1}.
        /// </summary>
        public static string TypeReadHelper_5 {
            get {
                return ResourceManager.GetString("TypeReadHelper.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - flags   {0}- file_num    {1}- bank name    {2}- entry meta size  {3}- entry name size  {4}- alignment    {5}.
        /// </summary>
        public static string WaveBank_1 {
            get {
                return ResourceManager.GetString("WaveBank.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Entry Meta Data Element Size is small.
        /// </summary>
        public static string WaveBank_2 {
            get {
                return ResourceManager.GetString("WaveBank.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - signature: {0}  big/network endian values.
        /// </summary>
        public static string WaveBankReader_1 {
            get {
                return ResourceManager.GetString("WaveBankReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - signature: {0}  little/intel endian values.
        /// </summary>
        public static string WaveBankReader_2 {
            get {
                return ResourceManager.GetString("WaveBankReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - version : {0}.
        /// </summary>
        public static string WaveBankReader_3 {
            get {
                return ResourceManager.GetString("WaveBankReader.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number  Size  Format  SamplingRate  Channels  BitDepth  Output   Path.
        /// </summary>
        public static string WaveBankReader_4 {
            get {
                return ResourceManager.GetString("WaveBankReader.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset : {0},format : {1},flags : {2},region_offset : {3},region_length : {4}.
        /// </summary>
        public static string WaveBankReader_5 {
            get {
                return ResourceManager.GetString("WaveBankReader.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - segment : {0}    offset : {1}    length : {2}({3}).
        /// </summary>
        public static string WaveBankReader_6 {
            get {
                return ResourceManager.GetString("WaveBankReader.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset: {0}.
        /// </summary>
        public static string XactClipReader_1 {
            get {
                return ResourceManager.GetString("XactClipReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track: {0}.
        /// </summary>
        public static string XactClipReader_2 {
            get {
                return ResourceManager.GetString("XactClipReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Play Wave Pitch Volume Filter Variation.
        /// </summary>
        public static string XactClipReader_3 {
            get {
                return ResourceManager.GetString("XactClipReader.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data Length: {0}.
        /// </summary>
        public static string XactSoundReader_1 {
            get {
                return ResourceManager.GetString("XactSoundReader.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Index: {0}.
        /// </summary>
        public static string XactSoundReader_2 {
            get {
                return ResourceManager.GetString("XactSoundReader.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is empty.
        /// </summary>
        public static string XNB_1 {
            get {
                return ResourceManager.GetString("XNB.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file &apos;{0}&apos;....
        /// </summary>
        public static string XNB_10 {
            get {
                return ResourceManager.GetString("XNB.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNB file validation successful!.
        /// </summary>
        public static string XNB_11 {
            get {
                return ResourceManager.GetString("XNB.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully read XNB file!.
        /// </summary>
        public static string XNB_12 {
            get {
                return ResourceManager.GetString("XNB.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting  {0}....
        /// </summary>
        public static string XNB_13 {
            get {
                return ResourceManager.GetString("XNB.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found valid XNB magic value!.
        /// </summary>
        public static string XNB_14 {
            get {
                return ResourceManager.GetString("XNB.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target platform: {0}.
        /// </summary>
        public static string XNB_15 {
            get {
                return ResourceManager.GetString("XNB.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNB format version: XNA Game Studio 3.{0}.
        /// </summary>
        public static string XNB_16 {
            get {
                return ResourceManager.GetString("XNB.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression: {0}.
        /// </summary>
        public static string XNB_17 {
            get {
                return ResourceManager.GetString("XNB.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} bytes..
        /// </summary>
        public static string XNB_18 {
            get {
                return ResourceManager.GetString("XNB.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressed size: {0} bytes..
        /// </summary>
        public static string XNB_19 {
            get {
                return ResourceManager.GetString("XNB.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file magic value, expected XNB, actual value is {0}.
        /// </summary>
        public static string XNB_2 {
            get {
                return ResourceManager.GetString("XNB.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading from byte position: {0}.
        /// </summary>
        public static string XNB_20 {
            get {
                return ResourceManager.GetString("XNB.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader count: {0}.
        /// </summary>
        public static string XNB_21 {
            get {
                return ResourceManager.GetString("XNB.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared resource count: {0}.
        /// </summary>
        public static string XNB_22 {
            get {
                return ResourceManager.GetString("XNB.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target platform found {0}..
        /// </summary>
        public static string XNB_23 {
            get {
                return ResourceManager.GetString("XNB.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XNB format version {0}..
        /// </summary>
        public static string XNB_24 {
            get {
                return ResourceManager.GetString("XNB.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNB file has been truncated!.
        /// </summary>
        public static string XNB_3 {
            get {
                return ResourceManager.GetString("XNB.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected shared resource ({0})..
        /// </summary>
        public static string XNB_4 {
            get {
                return ResourceManager.GetString("XNB.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object!.
        /// </summary>
        public static string XNB_5 {
            get {
                return ResourceManager.GetString("XNB.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file export!.
        /// </summary>
        public static string XNB_6 {
            get {
                return ResourceManager.GetString("XNB.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON file format: {0}.
        /// </summary>
        public static string XNB_7 {
            get {
                return ResourceManager.GetString("XNB.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file is empty..
        /// </summary>
        public static string XNB_8 {
            get {
                return ResourceManager.GetString("XNB.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing the &apos;content&apos; field..
        /// </summary>
        public static string XNB_9 {
            get {
                return ResourceManager.GetString("XNB.9", resourceCulture);
            }
        }
    }
}
